#!/usr/bin/env python3
import socket
import argparse
from concurrent.futures import ThreadPoolExecutor as TPL
from threading import Lock as lk
import threading
import time

parser = argparse.ArgumentParser(description="p0ckit subdomain enumerator")

group = parser.add_mutually_exclusive_group(required=True)
group.add_argument("--url", nargs="?", help="set the url for subdomain enumeration")
group.add_argument("--uw", "--url-wordlist", help="Use a list of url")

parser.add_argument("-w", "--wordlist", help="Use a list of subdomains")
parser.add_argument("-s", "--subdomain", nargs="+", type=str, help="Set the subdomain to test for")
parser.add_argument("-d", "--delay", nargs="?", const=2, type=int, help="Set delay between requests")
parser.add_argument("-wr", "--worker", nargs="?", default=20, type=int, help="Set how many worker to use")
args = parser.parse_args()

url = args.url
urlw = args.uw
sub = args.subdomain
dl = args.delay
wr = args.worker

stop_event = threading.Event()

def sub_chk(subt):
    if subt.endswith("."):
        return subt
    else:
        return subt + "."

def host_parser(url):
    if url.startswith(("https://", "http://")):
        host = url.split("://")[1]
    else:
        host = url
    return host if host else None

def host_chk_s(url, wordlist=None):
    if stop_event.is_set():
        return
    host = host_parser(url)
    if wordlist:
        with TPL(max_workers=wr) as execut:
            with open(wordlist, "r") as f:
                for l in f:
                    subt = l.strip()
                    sub = sub_chk(subt)
                    if args.delay:
                        time.sleep(dl)
                    execut.submit(host_dns_resolve, host, sub)
    else:
        for s in args.subdomain:
            su = s.strip()
            sub = sub_chk(su)
            if args.delay:
                time.sleep(dl)
            host_dns_resolve(host, sub)

def host_chk_m(uw, wordlist=None):
    if args.subdomain:
        with TPL(max_workers=wr) as execut:
            with open(uw, "r") as f:
                for l in f:
                    url = l.strip()
                    host = host_parser(url)
                    for s in args.subdomain:
                        su = s.strip()
                        sub = sub_chk(su)
                        if args.delay:
                            time.sleep(dl)
                        execut.submit(host_dns_resolve, host, sub)
    elif wordlist:
        with TPL(max_workers=wr) as execut:
            with open(uw, "r") as f:
                for l in f:
                    url = l.strip()
                    host = host_parser(url)
                    with open(wordlist, "r") as f2:
                        for l2 in f2:
                            subt = l2.strip()
                            sub = sub_chk(subt)
                            if args.delay:
                                time.sleep(dl)
                            execut.submit(host_dns_resolve, host, sub)
    else:
        sub = sub_chk(args.subdomain)
        with TPL(max_workers=wr) as execut:
            with open(uw, "r") as f:
                for l in f:
                    url = l.strip()
                    host = host_parser(url)
                    if args.delay:
                        time.sleep(dl)
                    execut.submit(host_dns_resolve, host, sub)

def host_dns_resolve(host, sub=None):
    if sub:
        fhost = f"{sub}{host}"
    else:
        fhost = host
    try:
        ip = socket.gethostbyname(fhost)
        print(f"Host: {fhost} -> {ip}")
    except socket.gaierror as e:
        print(f"Host: {fhost} -> {e}")


try:
    if args.url:
        host_chk_s(url, args.wordlist)
    elif args.uw:
        host_chk_m(urlw, args.wordlist)
except KeyboardInterrupt:
    stop_event.set()
    print("Ok quitting...")
    quit()
